vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'

        workshop_image:
            uri_prefix: /images/workshops
            upload_destination: '%kernel.project_dir%/public/images/workshops'
        
        training_image:
            uri_prefix: /images/training
            upload_destination: '%kernel.project_dir%/public/images/training'

        coaching_image:
            uri_prefix: /images/coaching
            upload_destination: '%kernel.project_dir%/public/images/coaching'
        
        event_image:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
